---
tags:
- functional
- functor
- aplicativo
layout: input_right
editor: code
type: problem
extra_visible: false
manual_evaluation: false
choices: []
name: 'Otro enfoque: separando responsabilidades'
