---
tags:
- data
- tiposalgebraicos
- functional
- functor
layout: input_bottom
editor: code
type: playground
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
name: Functores
