---
tags:
- functional
- functor
- aplicativo
- listas
- maybe
layout: input_right
editor: code
type: playground
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
name: Functores Aplicativos
